// Bambu printer "current stage" codes (stg_cur field).
// Sourced from greghesp/ha-bambulab CURRENT_STAGE_IDS const, which is the
// best-curated public reference. -1 / 255 both mean idle (no active stage).
export const CURRENT_STAGE_IDS: Record<number, string> = {
  [-1]: "idle",
  255: "idle",
  0: "printing",
  1: "auto bed leveling",
  2: "heatbed preheating",
  3: "sweeping XY mech mode",
  4: "changing filament",
  5: "M400 pause",
  6: "paused — filament runout",
  7: "heating hotend",
  8: "calibrating extrusion",
  9: "scanning bed surface",
  10: "inspecting first layer",
  11: "identifying build plate type",
  12: "calibrating micro lidar",
  13: "homing toolhead",
  14: "cleaning nozzle tip",
  15: "checking extruder temperature",
  16: "paused by user",
  17: "paused — front cover falling",
  18: "calibrating micro lidar",
  19: "calibrating extrusion flow",
  20: "paused — nozzle temperature malfunction",
  21: "paused — heat bed temperature malfunction",
  22: "unloading filament",
  23: "paused — skipped step",
  24: "loading filament",
  25: "calibrating motor noise",
  26: "paused — AMS lost",
  27: "paused — low fan speed (heat break)",
  28: "paused — chamber temperature control error",
  29: "cooling chamber",
  30: "paused by user G-code",
  31: "motor noise showoff",
  32: "paused — nozzle filament covered detected",
  33: "paused — cutter error",
  34: "paused — first layer error",
  35: "paused — nozzle clog",
  36: "checking absolute accuracy (pre)",
  37: "absolute accuracy calibration",
  38: "checking absolute accuracy (post)",
  39: "calibrating nozzle offset",
  40: "bed level (high temp)",
  41: "check quick release",
  42: "check door and cover",
  43: "laser calibration",
  44: "check platform",
  45: "check birdeye camera position",
  46: "calibrating birdeye camera",
  47: "bed level phase 1",
  48: "bed level phase 2",
  49: "heating chamber",
  50: "heated bed cooling",
  51: "printing calibration lines",
  52: "checking material",
  53: "calibrating live-view camera",
  54: "waiting for heatbed temperature",
  55: "checking material position",
  56: "calibrating cutter model offset",
  57: "measuring surface",
  58: "thermal preconditioning",
  59: "homing blade holder",
  60: "calibrating camera offset",
  61: "calibrating blade holder position",
  62: "hotend pick & place test",
  63: "waiting for chamber temperature to equalize",
  64: "preparing hotend",
  65: "calibrating nozzle clumping detection",
  66: "purifying chamber air",
  67: "measuring rotary attachment",
  68: "moving toolhead above purge chute",
  69: "cooling nozzle",
  70: "moving toolhead to center of heatbed",
  71: "active arc fitting",
  72: "hotend type detection",
  73: "build plate alignment detection",
  74: "heatbed surface foreign object detection",
  75: "heatbed underside foreign object detection",
  76: "pre-extrusion before printing",
  77: "preparing AMS",
};

export function describeStage(code: number | undefined): string | null {
  if (code == null) return null;
  return CURRENT_STAGE_IDS[code] ?? `stage ${code}`;
}

export const SPEED_PROFILE: Record<number, string> = {
  1: "silent",
  2: "standard",
  3: "sport",
  4: "ludicrous",
};

export function describeSpeed(level: number | undefined): string | null {
  if (level == null) return null;
  return SPEED_PROFILE[level] ?? `level ${level}`;
}
